package com.clilystudio.quiteread.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.clilystudio.quiteread.db.BookSyncRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BookSyncRecord".
*/
public class BookSyncRecordDao extends AbstractDao<BookSyncRecord, Void> {

    public static final String TABLENAME = "BookSyncRecord";

    /**
     * Properties of entity BookSyncRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property BookId = new Property(0, String.class, "bookId", false, "bookId");
        public final static Property Type = new Property(1, int.class, "type", false, "type");
        public final static Property Updated = new Property(2, java.util.Date.class, "updated", false, "updated");
        public final static Property UserId = new Property(3, String.class, "userId", false, "userId");
    }


    public BookSyncRecordDao(DaoConfig config) {
        super(config);
    }
    
    public BookSyncRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BookSyncRecord\" (" + //
                "\"bookId\" TEXT," + // 0: bookId
                "\"type\" INTEGER NOT NULL ," + // 1: type
                "\"updated\" INTEGER," + // 2: updated
                "\"userId\" TEXT);"); // 3: userId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BookSyncRecord\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BookSyncRecord entity) {
        stmt.clearBindings();
 
        String bookId = entity.getBookId();
        if (bookId != null) {
            stmt.bindString(1, bookId);
        }
        stmt.bindLong(2, entity.getType());
 
        java.util.Date updated = entity.getUpdated();
        if (updated != null) {
            stmt.bindLong(3, updated.getTime());
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(4, userId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BookSyncRecord entity) {
        stmt.clearBindings();
 
        String bookId = entity.getBookId();
        if (bookId != null) {
            stmt.bindString(1, bookId);
        }
        stmt.bindLong(2, entity.getType());
 
        java.util.Date updated = entity.getUpdated();
        if (updated != null) {
            stmt.bindLong(3, updated.getTime());
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(4, userId);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public BookSyncRecord readEntity(Cursor cursor, int offset) {
        BookSyncRecord entity = new BookSyncRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // bookId
            cursor.getInt(offset + 1), // type
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // updated
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // userId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BookSyncRecord entity, int offset) {
        entity.setBookId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setType(cursor.getInt(offset + 1));
        entity.setUpdated(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setUserId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(BookSyncRecord entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(BookSyncRecord entity) {
        return null;
    }

    @Override
    public boolean hasKey(BookSyncRecord entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
