package com.clilystudio.quiteread.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 1): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        RetweenRecordDao.createTable(db, ifNotExists);
        TocReadRecordDao.createTable(db, ifNotExists);
        BookSyncRecordDao.createTable(db, ifNotExists);
        BookVisitRecordDao.createTable(db, ifNotExists);
        MixTocRecordDao.createTable(db, ifNotExists);
        BookTopicEnterRecordDao.createTable(db, ifNotExists);
        BookDlRecordDao.createTable(db, ifNotExists);
        BookClickRecordDao.createTable(db, ifNotExists);
        PostUsefulRecordDao.createTable(db, ifNotExists);
        SourceWebReadRecordDao.createTable(db, ifNotExists);
        SyncAccountDao.createTable(db, ifNotExists);
        TweetCacheDao.createTable(db, ifNotExists);
        DownloadItemDao.createTable(db, ifNotExists);
        VoteRecordDao.createTable(db, ifNotExists);
        BookReadRecordDao.createTable(db, ifNotExists);
        SourceRecordDao.createTable(db, ifNotExists);
        DnsCacheRecordDao.createTable(db, ifNotExists);
        PostAgreeRecordDao.createTable(db, ifNotExists);
        BookFileDao.createTable(db, ifNotExists);
        AccountInfoDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        RetweenRecordDao.dropTable(db, ifExists);
        TocReadRecordDao.dropTable(db, ifExists);
        BookSyncRecordDao.dropTable(db, ifExists);
        BookVisitRecordDao.dropTable(db, ifExists);
        MixTocRecordDao.dropTable(db, ifExists);
        BookTopicEnterRecordDao.dropTable(db, ifExists);
        BookDlRecordDao.dropTable(db, ifExists);
        BookClickRecordDao.dropTable(db, ifExists);
        PostUsefulRecordDao.dropTable(db, ifExists);
        SourceWebReadRecordDao.dropTable(db, ifExists);
        SyncAccountDao.dropTable(db, ifExists);
        TweetCacheDao.dropTable(db, ifExists);
        DownloadItemDao.dropTable(db, ifExists);
        VoteRecordDao.dropTable(db, ifExists);
        BookReadRecordDao.dropTable(db, ifExists);
        SourceRecordDao.dropTable(db, ifExists);
        DnsCacheRecordDao.dropTable(db, ifExists);
        PostAgreeRecordDao.dropTable(db, ifExists);
        BookFileDao.dropTable(db, ifExists);
        AccountInfoDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(RetweenRecordDao.class);
        registerDaoClass(TocReadRecordDao.class);
        registerDaoClass(BookSyncRecordDao.class);
        registerDaoClass(BookVisitRecordDao.class);
        registerDaoClass(MixTocRecordDao.class);
        registerDaoClass(BookTopicEnterRecordDao.class);
        registerDaoClass(BookDlRecordDao.class);
        registerDaoClass(BookClickRecordDao.class);
        registerDaoClass(PostUsefulRecordDao.class);
        registerDaoClass(SourceWebReadRecordDao.class);
        registerDaoClass(SyncAccountDao.class);
        registerDaoClass(TweetCacheDao.class);
        registerDaoClass(DownloadItemDao.class);
        registerDaoClass(VoteRecordDao.class);
        registerDaoClass(BookReadRecordDao.class);
        registerDaoClass(SourceRecordDao.class);
        registerDaoClass(DnsCacheRecordDao.class);
        registerDaoClass(PostAgreeRecordDao.class);
        registerDaoClass(BookFileDao.class);
        registerDaoClass(AccountInfoDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
