package com.clilystudio.quiteread.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.clilystudio.quiteread.db.PostUsefulRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PostUsefulRecord".
*/
public class PostUsefulRecordDao extends AbstractDao<PostUsefulRecord, Void> {

    public static final String TABLENAME = "PostUsefulRecord";

    /**
     * Properties of entity PostUsefulRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property PostId = new Property(0, String.class, "postId", false, "postId");
        public final static Property Type = new Property(1, int.class, "type", false, "type");
        public final static Property UserId = new Property(2, String.class, "userId", false, "userId");
    }


    public PostUsefulRecordDao(DaoConfig config) {
        super(config);
    }
    
    public PostUsefulRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PostUsefulRecord\" (" + //
                "\"postId\" TEXT," + // 0: postId
                "\"type\" INTEGER NOT NULL ," + // 1: type
                "\"userId\" TEXT);"); // 2: userId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PostUsefulRecord\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PostUsefulRecord entity) {
        stmt.clearBindings();
 
        String postId = entity.getPostId();
        if (postId != null) {
            stmt.bindString(1, postId);
        }
        stmt.bindLong(2, entity.getType());
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(3, userId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PostUsefulRecord entity) {
        stmt.clearBindings();
 
        String postId = entity.getPostId();
        if (postId != null) {
            stmt.bindString(1, postId);
        }
        stmt.bindLong(2, entity.getType());
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(3, userId);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public PostUsefulRecord readEntity(Cursor cursor, int offset) {
        PostUsefulRecord entity = new PostUsefulRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // postId
            cursor.getInt(offset + 1), // type
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // userId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PostUsefulRecord entity, int offset) {
        entity.setPostId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setType(cursor.getInt(offset + 1));
        entity.setUserId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(PostUsefulRecord entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(PostUsefulRecord entity) {
        return null;
    }

    @Override
    public boolean hasKey(PostUsefulRecord entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
