package com.clilystudio.quiteread.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.clilystudio.quiteread.db.VoteRecord;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VoteRecords".
*/
public class VoteRecordDao extends AbstractDao<VoteRecord, Void> {

    public static final String TABLENAME = "VoteRecords";

    /**
     * Properties of entity VoteRecord.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Account_id = new Property(0, String.class, "account_id", false, "account_id");
        public final static Property Post_id = new Property(1, String.class, "post_id", false, "post_id");
        public final static Property Vote_item_index = new Property(2, int.class, "vote_item_index", false, "vote_item_index");
    }


    public VoteRecordDao(DaoConfig config) {
        super(config);
    }
    
    public VoteRecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VoteRecords\" (" + //
                "\"account_id\" TEXT," + // 0: account_id
                "\"post_id\" TEXT," + // 1: post_id
                "\"vote_item_index\" INTEGER NOT NULL );"); // 2: vote_item_index
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VoteRecords\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VoteRecord entity) {
        stmt.clearBindings();
 
        String account_id = entity.getAccount_id();
        if (account_id != null) {
            stmt.bindString(1, account_id);
        }
 
        String post_id = entity.getPost_id();
        if (post_id != null) {
            stmt.bindString(2, post_id);
        }
        stmt.bindLong(3, entity.getVote_item_index());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VoteRecord entity) {
        stmt.clearBindings();
 
        String account_id = entity.getAccount_id();
        if (account_id != null) {
            stmt.bindString(1, account_id);
        }
 
        String post_id = entity.getPost_id();
        if (post_id != null) {
            stmt.bindString(2, post_id);
        }
        stmt.bindLong(3, entity.getVote_item_index());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public VoteRecord readEntity(Cursor cursor, int offset) {
        VoteRecord entity = new VoteRecord( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // account_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // post_id
            cursor.getInt(offset + 2) // vote_item_index
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VoteRecord entity, int offset) {
        entity.setAccount_id(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setPost_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setVote_item_index(cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(VoteRecord entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(VoteRecord entity) {
        return null;
    }

    @Override
    public boolean hasKey(VoteRecord entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
